services:
    todo-app:
        build:
            context: ../
            dockerfile: ./todos-app/Dockerfile
        container_name: todo-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ../todos-app:/var/www/html
        environment:
            APP_NAME: ${APP_NAME}
            APP_ENV: ${APP_ENV}
            APP_DEBUG: ${APP_DEBUG}
            APP_KEY: ${APP_KEY}
            APP_VERSION: ${APP_VERSION}
            APP_URL: ${APP_URL}
            DB_CONNECTION: mysql
            DB_HOST: ${DB_HOST} # Asegúrate de que DB_HOST esté configurado en el archivo .env
            DB_PORT: 3306
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            MAIL_MAILER: ${MAIL_MAILER}
            MAIL_HOST: ${MAIL_HOST}
            MAIL_PORT: ${MAIL_PORT}
            MAIL_USERNAME: ${MAIL_USERNAME}
            MAIL_PASSWORD: ${MAIL_PASSWORD}
            MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}
            MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
            MAIL_FROM_NAME: ${MAIL_FROM_NAME}
        ports:
            - 8000:80
        networks:
            - todo-app-networks

    webserver:
        image: nginx:alpine
        container_name: todo-webserver
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ../todos-app:/var/www/html
            - ../todos-app/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - todo-app-networks
        depends_on:
            - todo-app

networks:
    todo-app-networks:
        driver: bridge
